### ISSUE TITLE
Failing to install on Mac

### ISSUE THREAD

**Issue by eligrumman** [ofekashery/mashov-covid19-clearance#3]
Logs .. I also did npm upgrade to make sure I have the latest of npm with `npm install -g npm@latest`  

```
➜  mashov-covid19-clearance git:(master) ✗ npm install
mashov-covid19-clearance@1.0.0 /Users/eliyahugromman/mashov-covid19-clearance
├── node-fetch@2.6.1
└─┬ node-schedule@1.3.2
  ├─┬ cron-parser@2.16.3
  │ ├─┬ is-nan@1.3.0
  │ │ └─┬ define-properties@1.1.3
  │ │   └── object-keys@1.1.1
  │ └─┬ moment-timezone@0.5.31
  │   └── moment@2.27.0
  ├── long-timeout@0.1.1
  └── sorted-array-functions@1.3.0

npm WARN mashov-covid19-clearance@1.0.0 No repository field.
➜  mashov-covid19-clearance git:(master) ✗ npm start

> mashov-covid19-clearance@1.0.0 start /Users/eliyahugromman/mashov-covid19-clearance
> node index.js

/Users/eliyahugromman/mashov-covid19-clearance/index.js:20
const login = async () => {
                    ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 18.7.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! mashov-covid19-clearance@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mashov-covid19-clearance@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mashov-covid19-clearance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mashov-covid19-clearance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mashov-covid19-clearance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eliyahugromman/mashov-covid19-clearance/npm-debug.log
```

**Comment by ofekashery** [comment]
It looks like you're using an old version of Node.js.
Please run ``node -v`` to check your Node.js version.

**Comment by ofekashery** [comment]
Please [update your Node.js](https://nodejs.org/en/download/) version to v12+.

**Comment by eligrumman** [comment]
Thanks, I suggest to made it clear in the readme
