### ISSUE TITLE
Failing to set cookie 

### ISSUE THREAD

**Issue by eligrumman** [ofekashery/mashov-covid19-clearance#6]
[2020-09-22T03:00:00] Logging in to your Mashov account...
(node:20817) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /root/mashov-covid19-clearance/index.js:44:76
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendClearances (/root/mashov-covid19-clearance/index.js:50:21)
(node:20817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

@ofekashery  If you can give me some direction, I'll try to resolve it. 

this error started on 20/9 according to my logs.

Thanks

**Comment by eligro** [comment]
see fixed PR for the cookie names .

however it says failed

```
[2020-11-01T06:31:46] Logging in to your Mashov account...
[2020-11-01T06:31:50] Running. Waiting for 06:00 IL
[2020-11-01T06:32:00] Logging in to your Mashov account...
[2020-11-01T06:32:02] Hello, גרומן מרב [אביתר ג1, נעמה ב2]!
[2020-11-01T06:32:03] Signature the clearance for אביתר failed.
[2020-11-01T06:32:03] Signature the clearance for נעמה failed.
```

where to start investigating?

**Comment by eligrumman** [comment]
fixed with the above code: 


```
[2020-11-01T06:39:52] Logging in to your Mashov account...
[2020-11-01T06:39:55] Running. Waiting for 06:00 IL
[2020-11-01T06:40:00] Logging in to your Mashov account...
[2020-11-01T06:40:02] Hello, גרומן מרב [אביתר ג1, נעמה ב2]!
[2020-11-01T06:40:03] The clearance was successfully signed for אביתר
[2020-11-01T06:40:03] The clearance was successfully signed for נעמה
```
